# docker-compose.yml


services:
  grader:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./submissions:/grading/submissions
      - ./input:/grading/input
      - ./expected_output:/grading/expected_output
      - ./summary:/grading/summary
      - ./logs:/grading/logs