version: '3.8'

services:
  grader:
    image: grading-env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./submissions:/grading/submissions
      - ./input:/grading/input
      - ./expected_output:/grading/expected_output
      - ./summary:/grading/summary