# docker-compose.yml



services:
  grader_ex0:
    build:
      context: ./ex0
      dockerfile: Dockerfile
    volumes:
      - ./ex0/submissions:/grading/submissions
      - ./ex0/input:/grading/input
      - ./ex0/expected_output:/grading/expected_output
      - ./ex0/summary:/grading/summary
      - ./ex0/logs:/grading/logs

  grader_ex1:
    build:
      context: ./ex1
      dockerfile: Dockerfile
    volumes:
      - ./ex1/submissions:/grading/submissions
      - ./ex1/input:/grading/input
      - ./ex1/summary:/grading/summary
      - ./ex1/logs:/grading/logs

  grader_ex2:
    build:
      context: ./ex2
      dockerfile: Dockerfile
    volumes:
      - ./ex2/submissions:/grading/submissions
      - ./ex2/input:/grading/input
      - ./ex2/summary:/grading/summary
      - ./ex2/logs:/grading/logs
  
  grader_ex3:
    build:
      context: ./ex3
      dockerfile: Dockerfile
    volumes:
      - ./ex3/submissions:/grading/submissions
      - ./ex3/summary:/grading/summary
      - ./ex3/logs:/grading/logs
  
  grader_ex4:
    build:
      context: ./ex4
      dockerfile: Dockerfile
    volumes:
      - ./ex4/submissions:/grading/submissions

      - ./ex4/summary:/grading/summary
      - ./ex4/logs:/grading/logs